# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_popularity', models.IntegerField()),
                ('length_of_url', models.IntegerField()),
                ('existing_dns_record', models.IntegerField()),
                ('age_of_domain', models.IntegerField()),
                ('ports', models.IntegerField()),
                ('reliable_ip', models.IntegerField()),
                ('shortened_url', models.IntegerField()),
                ('contains_at_the_rate', models.IntegerField()),
                ('cotains_double_slash', models.IntegerField()),
                ('contains_hyphen', models.IntegerField()),
                ('https_token', models.IntegerField()),
                ('subdomain_length', models.IntegerField()),
                ('has_https', models.IntegerField()),
                ('dns_record', models.IntegerField()),
                ('shortcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortner.URL')),
            ],
        ),
    ]
